### ISSUE TITLE
@channel Gets through muzzle

### ISSUE THREAD

**Issue by arrozconfrijoles** [dev-chat/mocker#8] opened 2019-06-27 21:00 UTC
**Describe the bug**
User can @channel while muzzled and it will occasionally be sent through muzzled and notify the entire group.

**To Reproduce**
reproduce error by muzzling Koz. 
Otherwise you probably could self-muzzle yourself and repeatedly spam @channel until one gets through

**Expected behavior**
@channel has to be a word that is completely eliminated by the muzzle. @here should also be eliminated

**Screenshots**
![image](https://user-images.githubusercontent.com/28546512/60300462-0f28f100-98fd-11e9-844c-0a6693d4a679.png)

**Comment by sfreeman422** [comment] 2019-06-29 17:16
This is successfully blocked .. sort of. The @channel will still get through given the fact that the app has to have a message successfully sent to the chat in order to then delete the original message and replace it with a muzzled message. The muzzled message however, will be properly muzzled. It is still unconfirmed whether or not everyone will get a notification on their phone when this happens. @arrozconfrijoles was seeing notifications however, it seems others may have not.. TBD.

**Comment by sfreeman422** [comment] 2019-06-30 18:31
Closing this issue. Since we cannot intercept messages before they hit Slack, we cannot reliably prevent @channel, @here and @user tags from causing a notification. We are choosing to instead punish offenders by increasing their muzzle by 5 minutes each time they tag any of the @'s mentioned above on PR #18

**Closed as completed by sfreeman422** 2019-06-30 18:31 UTC
Labels: help wanted
