### ISSUE TITLE
Add Ability for a Muzzle to Backfire

### ISSUE THREAD

**Issue by arrozconfrijoles** [dev-chat/mocker#3] opened 2019-06-25 16:57 UTC
1-5% of the time it should backfire and self-muzzle the muzzler

**Comment by sfreeman422** [comment] 2019-06-25 17:05
How long should the muzzler be muzzled for? Should we follow the standard random time between 30 seconds to 3 minutes?

**Comment by sfreeman422** [comment] 2019-07-05 18:08
A `backfire` means that a user attempted to muzzle someone but instead muzzled themselves based on some RNG. Needs followup and consensus from the group

**Comment by sfreeman422** [comment] 2019-11-27 20:17
Closing because this one is now being tested in prod.

**Comment by arrozconfrijoles** [comment] 2019-12-05 16:01
Backfire is working, but the muzzler can determine that they were backfired on when their target's messages get through without suppression. This leads to no one knowing that there had been a backfire.

**Solution**:
After the backfired muzzle's timer is up there should be a public flogging message sent to #gen (and possibly the original chat that the muzzle was shot from) saying who they attempted to shoot and calling them some pejorative. Possibly some rotating list of insults? 

Side addition: Maybe we could also link to some random inspirational quotes or some dumb Bros comments. I never see those slack loading messages anymore

**Alternatives**:
It could also immediately announce that it backfired. Some users have supported this version. A possible midpoint between the two aforementioned flogging announcements is too have the muzzle generated flogging go off 1 minute following the backfire, regardless of the length of the muzzle, 

The main reason I don't want the flogging message to immediately fire is it eliminates the chance for us to witness some organic backfire

**Comment by sfreeman422** [comment] 2019-12-10 00:27
Closing this because muzzle alerts will now be instant. Waiting delays too much of the experience and leaves users confused as to whether or not their muzzle actually went through. This sounds like it might result in more entertaining backfiring but it actually just results in confusion and claims that muzzle is broken.

**Comment by arrozconfrijoles** [comment] 2019-12-10 03:32
Disagree because the muzzlers claims of muzzle being broken will be muzzled. Only the backfired muzzler will be confused briefly.

**Comment by arrozconfrijoles** [comment] 2019-12-11 16:53
In an effort to encourage the usage of `/inventory` command under the #57 ticket we should increase the chance for a muzzle to backfire when someone has already used there 2 muzzles for an hour.

Currently it is unknown, and probably unlikely, if a muzzle could backfire on the third attempt of the hour. On the third attempt of the hour a backfire should occur 70%+ of the time. There should be some specific message to call them out for trying to break the rules.

**Comment by sfreeman422** [comment] 2019-12-13 19:33
It is confirmed that a muzzle cannot backfire on the third attempt of the hour, because that code is not accessed unless a muzzle is possible. Considering the option of adding a high chance backfire on a third muzzle attempt, but this feature request is on the backburner for now as there are larger, more important tickets to work on right now.

**Comment by sfreeman422** [comment] 2020-01-24 19:02
Create a new ticket for the third muzzle backfire. I don't think it is necessary and I don't particularly want to add it but if the rest of the team does, I will consider it.

**Closed as completed by sfreeman422** 2020-01-24 19:02 UTC
Labels: enhancement
